[toolchain]
package_manager = "yarn"
solana_version = "2.2.15"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
reptilx_contract_live = "PbQHuZDEW5EUHo3tbRAcRSqsHqKCxBhQMBV197ZsTiz"

[verifiable-build]
security_txt = "https://reptilxtoken.com/.well-known/security.txt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/reptilx-contract-live.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"