[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
reptilx_contract_live = "PbQHuZDEW5EUHo3tbRAcRSqsHqKCxBhQMBV197ZsTiz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/reptilx-contract-live.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
